version: "3.9"

services:
  poi:
    build: .
    command:  ./entrypoint.sh
    env_file: ./.envrc
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: ./.envrc
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U poi" ]
      interval: "10s"
      timeout: "5s"
      retries: 10